Fixed AdapterCacheRedis private methods (#27508)
ref https://linear.app/ghost/issue/HKG-1708

When a class instance is cloned, private method calls start to throw

  TypeError: Receiver must be an instance of class AdapterCacheRedis
      at AdapterCacheRedis.get (.../AdapterCacheRedis.js:206:54)

The api-framework pipeline clones the entire controller including the
cache adapter _.cloneDeep before wrapping each method, which 
causes this error when using in production. We've got a regression
test now to ensure we catch it in future.