🐛 Fixed newsletter not sending if locale is invalid
closes: https://linear.app/ghost/issue/ENG-1752
ref https://github.com/moment/luxon/blob/master/docs/intl.md

- We noticed the following error trace:
RangeError: Incorrect locale information provided
    at BatchSendingService.retryDb (/home/ghost/node_modules/@tryghost/email-service/lib/BatchSendingService.js:639:32)
    at new DateTimeFormat (<anonymous>)
    at getCachedDTF (/home/ghost/node_modules/luxon/build/node/luxon.js:621:11)
    at new PolyDateFormatter (/home/ghost/node_modules/luxon/build/node/luxon.js:842:16)
    at Locale.dtFormatter (/home/ghost/node_modules/luxon/build/node/luxon.js:1066:12)
    at Formatter.dtFormatter (/home/ghost/node_modules/luxon/build/node/luxon.js:2274:21)
    at Formatter.formatDateTime (/home/ghost/node_modules/luxon/build/node/luxon.js:2280:17)
    at DateTime.toLocaleString (/home/ghost/node_modules/luxon/build/node/luxon.js:6893:78)
    at formatDateLong (/home/ghost/node_modules/@tryghost/email-service/lib/EmailRenderer.js:45:74)
    at Object.getValue (/home/ghost/node_modules/@tryghost/email-service/lib/EmailRenderer.js:683:47)
    at /home/ghost/node_modules/@tryghost/email-service/lib/SendingService.js:158:36
    at Array.map (<anonymous>)
    at /home/ghost/node_modules/@tryghost/email-service/lib/SendingService.js:154:54
    at Array.map (<anonymous>)
    at SendingService.buildRecipients (/home/ghost/node_modules/@tryghost/email-service/lib/SendingService.js:151:24)
    at SendingService.send (/home/ghost/node_modules/@tryghost/email-service/lib/SendingService.js:127:33)
    at response.retryDb (/home/ghost/node_modules/@tryghost/email-service/lib/BatchSendingService.js:451:51)
- This is due to the locale being user-input - it can be set to any string.
- In our email sending code we pass the string to luxon to format dates, which errors if the locale is not valid according it Intl.
- This fix ensures that the locale is valid before passing it to luxon, falling back to en-gb if the locale is not valid